### PR TITLE
issue4

### PR DESCRIPTION
**Pull request by wunderfisch**
I made a new page, please review.

### CODE REVIEW

**Review by alirezarastineh — COMMENTED** [review]
Not a good change!
Try again

**Review by Madame-Aehm — CHANGES_REQUESTED** [review]
Marta, can you please change the h1 into an h2.

**Review by Madame-Aehm — APPROVED** [review]
This is exactly what I wanted. Good work.

**Review by alirezarastineh — APPROVED** [review]
Nice

**Pull request merged**
